#define __main 1
#define __int 2
#define __char 3
#define __if 4
#define __else 5
#define __for 6
#define __while 7
#define __return 8
#define __void 9
#define assign 21
#define plus 22
#define minus 23
#define multiply 24
#define divide 25
#define lParenth 26
#define rParenth 27
#define lSqBracket 28
#define rSqBracket 29
#define lCuBracket 30
#define rCubracket 31
#define comma 32
#define colon 33
#define semicolon 34
#define doubleQuote 35
#define singleQuote 36
#define __and 37
#define __or 38
#define __xor 39
#define __not 40
#define bigger 41
#define smaller 42
#define boe 43
#define soe 44
#define equal 45
#define notEqual 46
#define logicAnd 47
#define logicOr 48
#define letter 50
#define digit 51
#define ID 52
#define INT 53
#define STRING 54
