#define _main 1
#define _int 2
#define _char 3
#define _if 4
#define _else 5
#define _for 6
#define _while 7
#define _return 8
#define _void 9
#define assign 21
#define plus 22
#define minus 23
#define multiply 24
#define divide 25
#define lParenth 26
#define rParenth 27
#define lSqBracket 28
#define rSqBracket 29
#define lCuBracket 30
#define rCubracket 31
#define comma 32
#define colon 33
#define semicolon 34
#define doubleQuote 35
#define singleQuote 36
#define _and 37
#define _or 38
#define _xor 39
#define _not 40
#define bigger 41
#define smaller 42
#define boe 43
#define soe 44
#define equal 45
#define notEqual 46
#define logicAnd 47
#define logicOr 48
#define _letter 50
#define _digit 51
#define _ID 52
#define _INT 53
#define _STRING 54
